name: Build & Test & Publish

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      with:
        clean: false
        sparse-checkout-cone-mode: true
        sparse-checkout: |
          action
        filter: tree:0
        fetch-depth: 0

    - name: "Setup .NET"
      uses: "actions/setup-dotnet@v4"
      with:
        dotnet-quality: 'preview'
        dotnet-version: "9.x"

    - name: "Build"
      run: dotnet build --configuration Release --no-restore action
      shell: "bash"

    - name: "Test"
      run: dotnet run action/SharpValueInjector.Tests/SharpValueInjector.Tests.csproj
      shell: "bash"
