name: Build & Test & Publish

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v4"
      with:
        clean: false
        sparse-checkout-cone-mode: true
        sparse-checkout: |
          action
        filter: tree:0
        fetch-depth: 0
